ubuntu-jupyter:
  #build: .
  image: "ubuntu-jupyter:devel"
  ports:
    - "8888:8888"
  container_name: ubuntu-jupyter
  tty: true
  stdin_open: true
  environment:
    ENV: PROD
  volumes:
    - ~/notebook:/jupyter/notebook
    - ./conf:/jupyter/conf

